[mcp]

# نقاط نهاية Streamable HTTP (SHTTP)
shttp_servers = [
  { url = "https://openhands-agent-mcp-server.steve6546.repl.co/mcp", api_key = null }
]

# نقاط نهاية Server-Sent Events (SSE)
sse_servers = [
  "https://openhands-agent-mcp-server.steve6546.repl.co/mcp/sse"
]

# عمليات محليّة عبر stdin/stdout (STDIO) — اختياري
stdio_servers = [
  { name = "fetch", command = "uvx", args = ["mcp-server-fetch"] }
]