// tools/structureGenerator.js - أداة توليد هيكل المشروع حسب الفكرة
const fs   = require('fs');
const path = require('path');

/**
 * يولّد ملفات هيكلية بناءً على قائمة المهام.
 * @param {string[]} tasks - أسماء المهام من ideaGenerator
 * @returns {{ files: Record<string,string> }}
 */
module.exports = async function structureGenerator(tasks) {
  const files = {};

  // إنشاء README
  if (tasks.includes('setup_repo')) {
    files['README.md'] =
      '# New OpenHands Project\n\n' +
      'Generated by scaffold_generator.\n';
  }

  // هيكل front/backend
  if (tasks.includes('init_scaffold')) {
    files['frontend/src/index.tsx'] =
      `import React from 'react';\n\n` +
      `console.log('Hello OpenHands');\n`;
    files['backend/index.js'] =
      `const express = require('express');\n` +
      `const app = express();\n` +
      `app.listen(process.env.PORT || 3000, () =>\n` +
      `  console.log('Backend running')\n` +
      `);\n`;
  }

  // يمكنك هنا إضافة المزيد من القوالب (config, .gitignore, tests…)
  return { files };
};